app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

JMSTranslationBundle_ui:
    resource: @JMSTranslationBundle/Controller/
    type:     annotation
    prefix:   /_trans

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_user_bundle:
    resource: @UserBundle/Resources/config/routing.yml

#Translation_sr:
#    resource: '@AppBundle/Resources/translations/routes.sr.yml'

#Translation_en:
#    resource: '@AppBundle/Resources/translations/routes.en.yml'