# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_MODERATOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4

            logout:
                path: fos_user_security_logout
                target: home
            anonymous:    true

    access_control:
        - { path: ^/(sr|en)/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(sr|en)/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(sr|en)/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(sr|en)/admin, roles: ROLE_ADMIN }
